### ISSUE TITLE
Checks, mates and stalemates detection

### ISSUE THREAD

**Issue by Szaroslav** [agh-cs-imbeciles/python-laser-chess#36]

**Comment by Szaroslav** [comment]
- [ ] Check
- [ ] Mate

**Comment by Szaroslav** [comment]
![image](https://user-images.githubusercontent.com/54867641/230909367-8687b702-9b25-4757-9536-2496473d0c8e.jpeg)

**Comment by kpiotr6** [comment]
Done with 2 methods in CheckManger:
-is_checkmate()
-is_stalemate()
