### ISSUE TITLE
En passant bug

### ISSUE THREAD

**Issue by kpiotr6** [agh-cs-imbeciles/python-laser-chess#80]
En passant move type is recognized when it should not be. It occurs when capturing any piece, which is in last rank, by a pawn. This causes piece in penultimate rank to disapear

![Image](https://github.com/agh-cs-imbeciles/python-laser-chess/assets/114953716/3aec4451-c93a-4ea1-809d-3356ca25f603)

![Image](https://github.com/agh-cs-imbeciles/python-laser-chess/assets/114953716/881589a6-9842-4c0a-826e-acbee78cb181)

**Comment by Szaroslav** [comment]
Finished.
